### ISSUE TITLE
Zoom Video conferencing screen sharing dark overlay

### ISSUE THREAD

**Issue by miclaraia** [regolith-linux/regolith-compositor-compton-glx#3]
It looks like compton and Zoom aren't getting along again. I found [this](https://github.com/regolith-linux/regolith-compton-config/issues/2) issue in the old regolith compton repository. It looks like what happened is that the zoom overlay window in question now has the name `cpt_frame_xcb_window`, and the exception in the compton config is coded for `cpt_frame_window`

https://github.com/regolith-linux/regolith-compositor-compton-glx/blob/master/config#L82

**Comment by kgilmer** [comment]
@miclaraia wow, thanks!  I've updated both the picom and compton configs.  This change will be available in Regolith 2, but will not be back ported to Regolith 1.x.  You're free to include this change locally by providing your own `compton` config file in `$HOME/.config/regolith/compton/config`

**Comment by fadli0029** [comment]
There's another solution for this: 
`zoom->settings->share screen->advance->uncheck "show green border around the shared content"`

I assume that the green border feature is to let the screen sharer know which part of his/her screen is made visible to viewers. If you don't care or are completely aware of what you're sharing, then unchecking that feature is not an issue.

https://www.reddit.com/r/archlinux/comments/idpfsv/comment/hv9xx99/?utm_source=share&utm_medium=web2x&context=3
